package com.legal.lawconnect.functions;

import org.springframework.stereotype.Component;

@Component
public class ToHtml {
    public String getVerificationHtmlCode(String resetLink){
        return          "<!DOCTYPE html>"
                        + "<html lang=\"en\">"
                        + "<head>"
                        + "<meta charset=\"UTF-8\">"
                        + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                        + "<title>Password Reset</title>"
                        + "<style>"
                        + "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');"
                        + "body {"
                        + "font-family: 'Inter', sans-serif;"
                        + "line-height: 1.6;"
                        + "color: #1f2937;"
                        + "background-color: #f3f4f6;"
                        + "margin: 0;"
                        + "padding: 0;"
                        + "}"
                        + ".container {"
                        + "max-width: 600px;"
                        + "margin: 2rem auto;"
                        + "background-color: #ffffff;"
                        + "border-radius: 0.5rem;"
                        + "overflow: hidden;"
                        + "box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);"
                        + "}"
                        + ".header {"
                        + "background-color: #1e3a8a;"
                        + "color: white;"
                        + "padding: 1.5rem;"
                        + "text-align: center;"
                        + "border-bottom: 4px solid #3b82f6;"
                        + "}"
                        + ".content {"
                        + "padding: 2rem;"
                        + "}"
                        + ".footer {"
                        + "text-align: center;"
                        + "padding: 1.5rem;"
                        + "font-size: 0.75rem;"
                        + "color: #6b7280;"
                        + "border-top: 1px solid #e5e7eb;"
                        + "background-color: #f9fafb;"
                        + "}"
                        + ".button {"
                        + "display: inline-block;"
                        + "padding: 0.75rem 1.5rem;"
                        + "background-color: #1e3a8a;"
                        + "color: white !important;"
                        + "text-decoration: none;"
                        + "border-radius: 0.375rem;"
                        + "font-weight: 500;"
                        + "margin: 1.5rem 0;"
                        + "}"
                        + ".button:hover {"
                        + "background-color: #1d4ed8;"
                        + "}"
                        + ".expiry-note {"
                        + "color: #6b7280;"
                        + "font-size: 0.875rem;"
                        + "margin-top: 1.5rem;"
                        + "}"
                        + ".support {"
                        + "margin-top: 1.5rem;"
                        + "font-size: 0.875rem;"
                        + "color: #4b5563;"
                        + "}"
                        + "</style>"
                        + "</head>"
                        + "<body>"
                        + "<div class=\"container\">"
                        + "<div class=\"header\">"
                        + "<h1 style=\"margin: 0; font-size: 1.5rem; font-weight: 600;\">Password Reset</h1>"
                        + "<p style=\"margin: 0.5rem 0 0; opacity: 0.9;\">LawConnect Account Security</p>"
                        + "</div>"
                        + "<div class=\"content\">"
                        + "<p style=\"margin: 0 0 1rem;\">Hello,</p>"
                        + "<p style=\"margin: 0 0 1.5rem;\">We received a request to reset your LawConnect account password. Click the link below to reset your password:</p>"
                        + "<p><a href=\"" + resetLink + "\">Reset Password</a></p>"
                        + "<p class=\"expiry-note\">This link will expire in 10 minutes for security reasons.</p>"
                        + "<p style=\"margin: 1.5rem 0 0;\">If you didn't request this password reset, please ignore this email or contact support if you have concerns.</p>"
                        + "<p class=\"support\">Need help? Contact our support team at <a href=\"mailto:support@lawconnect.com\" style=\"color: #3b82f6;\">support@lawconnect.com</a></p>"
                        + "</div>"
                        + "<div class=\"footer\">"
                        + "<p style=\"margin: 0;\">&copy; 2025 LawConnect. All rights reserved.</p>"
                        + "<p style=\"margin: 0.5rem 0 0;\">123 Legal Street, Suite 100, Lawville, LV 12345</p>"
                        + "</div>"
                        + "</div>"
                        + "</body>"
                        + "</html>";
    }
}
